/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import modelo.Juego;
import controlador.RegistroJuego;

/**
 *
 * @author CETECOM
 */
public class VentanaAgregar extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAgregar
     */
    public VentanaAgregar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        txtNombre_juego = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtPrecio_juego = new javax.swing.JTextField();
        rdNoes_multijugador = new javax.swing.JRadioButton();
        rdEs_multijugador = new javax.swing.JRadioButton();
        btnGrabar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtId_juego = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rdOferta = new javax.swing.JRadioButton();
        rdNormal = new javax.swing.JRadioButton();
        btnModificar = new javax.swing.JButton();
        cmbTIpoJuego = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtNombre_juego.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        txtDescripcion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        txtPrecio_juego.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        buttonGroup1.add(rdNoes_multijugador);
        rdNoes_multijugador.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        rdNoes_multijugador.setSelected(true);
        rdNoes_multijugador.setText("NO");
        rdNoes_multijugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdNoes_multijugadorActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdEs_multijugador);
        rdEs_multijugador.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        rdEs_multijugador.setText("SI");
        rdEs_multijugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdEs_multijugadorActionPerformed(evt);
            }
        });

        btnGrabar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnGrabar.setText("GRABAR");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Ingreso de Juegos");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("ID_juego");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Nombre del juego");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Descripción");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Valor  $");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Multijugador");

        txtId_juego.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setText("Tipo de Juego");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setText("En Oferta");

        buttonGroup2.add(rdOferta);
        rdOferta.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        rdOferta.setText("SI");
        rdOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdOfertaActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdNormal);
        rdNormal.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        rdNormal.setSelected(true);
        rdNormal.setText("NO");

        btnModificar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        cmbTIpoJuego.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        cmbTIpoJuego.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acción Aventura", "Acción RPG", "Battle Royale", "Deportes", "Lucha", "MOBA", "Party", "RPG", "Shooter", "Simulación", "Supervivencia", "Tactical Shooter", " " }));
        cmbTIpoJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTIpoJuegoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtNombre_juego, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtId_juego, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtPrecio_juego)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(rdEs_multijugador)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(rdNoes_multijugador))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(rdOferta)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(rdNormal)))
                                            .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                                        .addComponent(cmbTIpoJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId_juego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre_juego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbTIpoJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rdEs_multijugador)
                    .addComponent(rdNoes_multijugador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(rdOferta)
                    .addComponent(rdNormal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPrecio_juego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGrabar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        // vamos a crear un objeto Producto
        Juego juego = new Juego();
        // los "seteamos", es decir, cargamos los datos con los setter
        juego.setId_juego(this.txtId_juego.getText().trim().toUpperCase());
        juego.setNombre_juego(this.txtNombre_juego.getText().trim());
        juego.setDescripcion(this.txtDescripcion.getText().trim());
        juego.setPrecio_juego(Integer.parseInt(
                this.txtPrecio_juego.getText().trim()));
        // la información de los radioButton
        if (this.rdEs_multijugador.isSelected()) {
            juego.setEs_multijugador(true);
        } else {
            juego.setEs_multijugador(false);
        }
        if (this.rdOferta.isSelected()) {
            juego.setOferta(true);
        } else {
            juego.setOferta(false);
        }
        juego.setTipoJuego(this.cmbTIpoJuego.getSelectedItem().toString());

        // ahora grabamos a traves del controlador
        if (new RegistroJuego().agregarJuego(juego)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Juego Agregado a la base de datos...");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "NO Grabó!!!");
        }

    }//GEN-LAST:event_btnGrabarActionPerformed

    private void rdEs_multijugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdEs_multijugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdEs_multijugadorActionPerformed

    private void rdNoes_multijugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdNoes_multijugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdNoes_multijugadorActionPerformed

    
    
    
    
    
    private void cmbTIpoJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTIpoJuegoActionPerformed
      
    }//GEN-LAST:event_cmbTIpoJuegoActionPerformed

    private void rdOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdOfertaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdOfertaActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        Juego juego = new Juego();

        juego.setId_juego(this.txtId_juego.getText().trim().toUpperCase());
        juego.setNombre_juego(this.txtNombre_juego.getText().trim().toUpperCase());
        juego.setDescripcion(this.txtDescripcion.getText().trim().toUpperCase());
        juego.setPrecio_juego(Integer.parseInt(this.txtPrecio_juego.getText().trim()));

        if (this.rdEs_multijugador.isSelected()) {
            juego.setEs_multijugador(true);
        } else {
            juego.setEs_multijugador(false);
        }

        if (this.rdOferta.isSelected()) {
            juego.setOferta(true);
        } else {
            juego.setOferta(false);
        }

        if (new RegistroJuego().modificarJuego(juego)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Registro modificado");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "no modificó");
        }

    }//GEN-LAST:event_btnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAgregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnModificar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cmbTIpoJuego;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton rdEs_multijugador;
    private javax.swing.JRadioButton rdNoes_multijugador;
    private javax.swing.JRadioButton rdNormal;
    private javax.swing.JRadioButton rdOferta;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtId_juego;
    private javax.swing.JTextField txtNombre_juego;
    private javax.swing.JTextField txtPrecio_juego;
    // End of variables declaration//GEN-END:variables
}
